### ISSUE TITLE
Allow localhost services on dev environment to be seen by containers

### ISSUE THREAD

**Issue by dnk8n** [nhost/cli#501] opened 2022-12-19 12:29 UTC
E.g. In docker compose, which I believe nhost uses indirectly, the following is needed

```
extra_hosts:
      - "host.docker.internal:host-gateway"
```

Use-case, I have some non-dockerized services as part of my stack. I want hasura to be able to target them and test remote schemas locally before I proceed to production

**Comment by elephant3** [comment] 2022-12-28 12:32
`host.docker.internal` should be already available in your containers to resolve to the host machine. See https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host

**Comment by elephant3** [comment] 2023-01-03 17:02
@dnk8n do you use Linux? Apparently `host.docker.internal` seems to be not available on Linux, I didn't know that. I'll make sure it's added in the next release

**Comment by dnk8n** [comment] 2023-01-03 19:06
Yes, I use Linux. That might be the issue. I was sure I didn't have access
but will check again as soon as I can

**Comment by elephant3** [comment] 2023-01-16 17:56
@dnk8n please check the latest CLI release and let me know if the issue is fixed for you.

**Comment by dnk8n** [comment] 2023-01-23 16:42
I upgraded to Nhost CLI v0.8.21 for linux-amd64 and it works!

E.g. of an environment variable I have in my .env.development file:

```
SENDFORM_URL=http://host.docker.internal:8000/api/sendform
```

**Comment by elephant3** [comment] 2023-01-23 17:13
@dnk8n awesome! Closing the issue.

**Closed by elephant3** 2023-01-23 17:13 UTC
