### ISSUE TITLE
The nhost dev command fails with multiple errors

### ISSUE THREAD

**Issue by atapas** [nhost/cli#237] opened 2022-06-06 09:06 UTC
**Describe the bug**
I've been using nhost for a while now. The `nhost dev` command from CLI fails with multiple erros.

**To Reproduce**
1. Followed the steps mentioned here: https://docs.nhost.io/platform/overview/get-started-with-nhost-cli
2. the cli got installed successfully and able to get the nhost project locally.
3. However the `nhost dev` doesn't work 90% cases. It fails with multiple errors(mentioned below).

**Expected behavior**
The `nhost dev` command should work successfully.

**Screenshots**

With `nhost dev --debug`

SMTP Port eror for both 1893 1894

![image](https://user-images.githubusercontent.com/3633137/172130246-1f5bdccb-825c-435a-b64e-ce40bb9c5be2.png)

Then changed the port to 1895. The services were coming up but failed with the following error(Health Check un successful)

![image](https://user-images.githubusercontent.com/3633137/172130489-a4944bf1-c656-4130-82f9-d61887f47c53.png)

Here is the log for the nhost_hasura service

![image](https://user-images.githubusercontent.com/3633137/172130735-2b69466e-a226-4667-b32c-8d13bb82c288.png)

Here is the log of nhost_auth service

![image](https://user-images.githubusercontent.com/3633137/172130865-db3448bb-0378-40e4-bbe1-ac0b23acfc82.png)

Log of nhost_storage service

![image](https://user-images.githubusercontent.com/3633137/172130976-3d0323e9-38b2-402d-af26-a3196981e2c2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.x
 
**Additional context**
I have github and docker installed and docker was running while executing the commands. The nhost dev worked once in last 10 times yesterday. Today not working with any attempt, without any changes.

**Comment by dbarrosop** [comment] 2022-06-06 09:57
Can you show the logs for the postgres container? I think the issue is going to be there.

**Comment by atapas** [comment] 2022-06-06 10:24
> Can you show the logs for the postgres container? I think the issue is going to be there.

Could you please gimme the command to fetch that from my ubuntu box?

**Comment by atapas** [comment] 2022-06-06 10:37
> > Can you show the logs for the postgres container? I think the issue is going to be there.
> 
> Could you please gimme the command to fetch that from my ubuntu box?

@dbarrosop Is this the one?

![image](https://user-images.githubusercontent.com/3633137/172145234-7f0719cb-dc73-4c72-b0fb-ccd3838ef928.png)

**Comment by dbarrosop** [comment] 2022-06-06 11:52
Are those from the same run? It is a bit strange because postgres says it is listening on port 5139 but the containers are trying to connect to port 5739. For instance:

hasura-storage:

```
time="2022-06-06T09:03:48Z" level=error msg="problem applying postgres migrations: problem creating postgres driver: dial tp 172.18.0.3:5739: connect: connection timed
out"
```

postgres:

```
2022-06-06 07:12:56.249 UTC [11 LOG: listening on IPV4 address "0.0.0.0" port 5139
```

**Comment by atapas** [comment] 2022-06-06 11:57
> Are those from the same run? It is a bit strange because postgres says it is listening on port 5139 but the containers are trying to connect to port 5739. For instance:
> 
> hasura-storage:
> 
> ```
> time="2022-06-06T09:03:48Z" level=error msg="problem applying postgres migrations: problem creating postgres driver: dial tp 172.18.0.3:5739: connect: connection timed out"
> ```
> 
> postgres:
> 
> ```
> 2022-06-06 07:12:56.249 UTC [11 LOG: listening on IPV4 address "0.0.0.0" port 5139
> ```

No the postgres one from the separate run.However the outsome is the same. 

![image](https://user-images.githubusercontent.com/3633137/172155884-44ee270d-7964-4620-8c38-9f52cf5b357b.png)

Other logs from the same run
![image](https://user-images.githubusercontent.com/3633137/172156073-ebcfa5ec-c6b6-4e68-a714-27ede6c29748.png)


![image](https://user-images.githubusercontent.com/3633137/172156118-ecb1e85d-da46-4a5e-8890-7074c81fb6a7.png)

![image](https://user-images.githubusercontent.com/3633137/172156208-d43c84fd-64ae-4cef-a018-0efa705d0bec.png)

**Comment by atapas** [comment] 2022-06-21 04:19
Hi Team,

Any update/workaround with this issue?

**Comment by dbarrosop** [comment] 2022-06-21 06:15
We are working on replacing some of the internal magic with plain `docker-compose`. This should make things easier to troubleshoot and also increase compatibility with various environments. I don't have an exact timeframe but hopefully we will have something in a couple of weeks.

**Comment by MPK1** [comment] 2022-07-13 17:44
I actually encounter the exact same problem as @sebpalluel on my M1 Mac. On Debian, everything works fine. The created db_data directory is not owned by postgres(999).

**Comment by elitan** [comment] 2022-08-19 11:01
This is fixed in the latest release (with docker compose).

**Closed by elitan** 2022-08-19 11:01 UTC
