### ISSUE TITLE
Installation command fails with 404 error

### ISSUE THREAD

**Issue by alimony** [nhost/cli#156] opened 2022-02-23 11:16 UTC
**Describe the bug**
I get an error when running the install command from the README.

**To Reproduce**
1. Run `sudo curl -L https://raw.githubusercontent.com/nhost/cli/main/get.sh | bash`

**Expected behavior**
That nhost is installed.

**Desktop (please complete the following information):**
 - OS: macOS 12.1 (M1 Pro chip)
 - Browser: None
 - Version: None

**Additional context**
See full command output:
```
sudo curl -L https://raw.githubusercontent.com/nhost/cli/main/get.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3408  100  3408    0     0  44627      0 --:--:-- --:--:-- --:--:-- 47333
--> Getting latest version...
--> Latest version is mentions_count
--> Downloading Nhost mentions_count for darwin-arm64 to cli-mentions_count-darwin-arm64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
FAILED> failed executing: curl -L -f -o cli-mentions_count-darwin-arm64.tar.gz https://github.com/nhost/cli/releases/download/mentions_count/cli-mentions_count-darwin-arm64.tar.gz
```

**Comment by nunopato** [comment] 2022-02-24 21:46
@alimony is this still happening to you? I am not able to reproduce this issue.

**Comment by alimony** [comment] 2022-02-28 14:42
Yes. It's trying to download `https://github.com/nhost/cli/releases/download/mentions_count/cli-mentions_count-darwin-arm64.tar.gz` which does not exist.

**Comment by alimony** [comment] 2022-02-28 14:49
This line seems to set the incorrect version: https://github.com/nhost/cli/blob/main/get.sh#L44

If I download the JSON response manually, pretty print it, then run the grep and sed, I get the correct value.

Does the above line expect the response to be pretty printed? Because my curl downloads it as compressed.

**Comment by elitan** [comment] 2022-08-19 10:56
This issue should be fixed in the latest version. Let me know if you still have this issue.

**Closed by elitan** 2022-08-19 10:56 UTC
