### ISSUE TITLE
Subdomain flag ignored in `nhost config show` command

### ISSUE THREAD

**Issue by spakanati** [nhost/cli#748] opened 2023-07-20 09:29 UTC
The subdomain flag does not seem to work in the `nhost config show` command.

To reproduce, try running:
`nhost config show --subdomain=XXX`
This always shows local config and completely ignores subdomain flag

By contrast, the validate command works:
`nhost config validate --subdomain=XXX`
This will validate remote config for subdomain XXX

I am using v1.5.0

**Comment by dbarrosop** [comment] 2023-07-20 09:53
I just checked and this seems to work as intended. Keep in mind the following:

```nhost config show --help
NAME:
   nhost config show - Shows configuration after resolving secrets

USAGE:
   nhost config show [command options] [arguments...]

DESCRIPTION:
   Note that this command will always use the local secrets, even if you specify subdomain
...
```

So this command is mostly useful to verify [overlays](https://docs.nhost.io/cli/overlays).

And if you are wondering why we use local secrets, it is for privacy reasons. So you can basically use `validate` to verify you have your secrets defined and `show` to make sure they resolve as intended (even if it's using local secrets) and to verify overlays.

**Comment by dbarrosop** [comment] 2023-08-01 05:58
> to combine the overlay for the correct subdomain with the local config

The idea is to test what you are going to push is what you want/correct within a certain degree of confidence.

> without being able to see the secret in any way (either in cloud project or via cli) it makes it hard to debug syntax errors with the tool file

I understand, this is about striking a balance without convenience and security and for now we are siding on the side of security.

I am closing this one for now but I am happy to keep discussing this if you think it's really a problem. Even though showing the secrets is probably not going to change for now we may want to explore altneratives to validating the configuration remotely if this is really a problem.

**Closed by dbarrosop** 2023-08-01 05:58 UTC
