### ISSUE TITLE
Cannot use arrays with .secrets and .toml file 

### ISSUE THREAD

**Issue by ArieJones** [nhost/cli#730] opened 2023-06-16 16:31 UTC
It appears maybe the replacement code needs to be updated in order to accommodate some way in which we can use arrays 

If we try to do something like this 

![image](https://github.com/nhost/cli/assets/14859781/8c1b5d5e-f196-419d-908a-50470c0f02bf)

we get the following error 

![image](https://github.com/nhost/cli/assets/14859781/2d463ff0-0b3c-4552-8fbe-d3f05014f5da)

if we try to put the secrets key in as something like 'value1','value2' then that is a no-go for the secrets file. 

Obviously, since the new setup requires us to have secrets if we are changing values between different environments.... we would need this to work since we have to explicitly allow some wildcard urls in order to use redirectTo with auth

**Comment by dbarrosop** [comment] 2023-06-16 17:09
This is working as intended. You can do the following:

```
allowedUrls = ['{{ secrets.ALLOWED_URLS_ASD }}', '{{ secrets.ALLOWED_URLS_QWE }}']
```

> since the new setup requires us to have secrets if we are changing values between different environments.... 

You can also use [overlays](https://docs.nhost.io/cli/overlays) which might be a more robust solution for what you are trying to do

**Comment by dbarrosop** [comment] 2023-06-25 05:57
Closing this one as I don't think there is anything broken here, feel free to re-open otherwise.

**Closed by dbarrosop** 2023-06-25 05:57 UTC
