### ISSUE TITLE
Health checks for containers fail

### ISSUE THREAD

**Issue by Herohtar** [nhost/cli#148] opened 2022-02-06 05:20 UTC
**Describe the bug**
When I try to run `nhost dev`, it gets stuck during the health check for the `nhost_auth`, `nhost_storage`, and `nhost_hasura` containers.

**To Reproduce**
1. Run `nhost dev`
2. Wait

**Expected behavior**
NHost dev environment should start up successfully.

**Screenshots**
CLI output:
```
> Initializing environment
> [nhost] [prefix] Fetching containers
> Wrapping containers into environment
> [path] Watching .git/HEAD
> Fetching local git branch
> git HEAD not found
> Parsing app configuration
> [nhost_hasura] [configuration] Initializing
> [nhost_auth] [configuration] Initializing
> [nhost_storage] [configuration] Initializing
> [nhost_mailhog] [configuration] Initializing
> [nhost_postgres] [configuration] Initializing
> [nhost_minio] [configuration] Initializing
> [watcher] Activated
> Server logs will be deleted on shutdown.
> Checking for required Nhost container images
> [minio/minio:RELEASE.2021-09-24T00-24-24Z] Pulling container image
> [mailhog/mailhog:v1.0.1] Pulling container image
> [nhost/hasura-auth:sha-994af31] Pulling container image
> [nhost/hasura-storage:sha-623f285] Pulling container image
> [nhost/postgres:12-v0.0.6] Pulling container image
> [hasura/graphql-engine:v2.1.0] Pulling container image
> Configuring services
> [data] Mounting data from  .nhost/main
> [nhost] [network] Preparing
> [nhost] [network] Fetching
> [nhost_hasura] [container] Creating
> [nhost_hasura] [container] Starting
> [nhost_minio] [container] Creating
> [nhost_minio] [container] Starting
> [nhost_postgres] [container] Creating
> [nhost_postgres] [container] Starting
> [nhost_auth] [container] Creating
> [nhost_auth] [container] Starting
> [nhost_storage] [container] Creating
> [nhost_storage] [container] Starting
> [nhost_mailhog] [container] Creating
> [nhost_mailhog] [container] Starting
> [nhost] [prefix] Fetching containers
> Wrapping containers into environment
> Starting health check
> [nhost_auth] [container] Health check attempt #1 unsuccessful
> [nhost_storage] [container] Health check attempt #1 unsuccessful
> [nhost_hasura] [container] Health check attempt #1 unsuccessful
> [nhost_hasura] [container] Health check attempt #2 unsuccessful
> [nhost_storage] [container] Health check attempt #2 unsuccessful
> [nhost_auth] [container] Health check attempt #2 unsuccessful
> [nhost_auth] [container] Health check attempt #3 unsuccessful
> [nhost_hasura] [container] Health check attempt #3 unsuccessful
> [nhost_storage] [container] Health check attempt #3 unsuccessful
> [nhost_auth] [container] Health check attempt #4 unsuccessful
> [nhost_hasura] [container] Health check attempt #4 unsuccessful
> [nhost_storage] [container] Health check attempt #4 unsuccessful
.
.
.
... infinite list of unsuccessful health checks
```

**Desktop (please complete the following information):**
 - OS: Fedora 35 x64
 - Browser: N/A
 - Version: Nhost CLI v0.6.1 for linux-amd64

**Additional context**
I am using Podman instead of Docker, so I had to manually pull the images because the CLI doesn't specify the registry for the containers (as mentioned [here](https://github.com/nhost/cli/issues/139#issuecomment-1030707527)). Not sure if that could be causing the issue.

**Comment by mrinalwahal** [comment] 2022-02-06 19:05
Just restart the CLI in debug mode. And check your container logs from Docker engine. Check specifically for Hasura logs and Auth logs.

You will see where the problem is. Then we can help you out better in troubleshooting.

**Comment by Herohtar** [comment] 2022-02-06 21:35
It looks like the problem is Postgres... the `nhost_postgres` logs are full of this repeated set of lines:
```
find: ‘/var/lib/postgresql/data’: Permission denied
chown: changing ownership of '/var/lib/postgresql/data': Permission denied
chmod: changing permissions of '/var/lib/postgresql/data': Permission denied
```

`nhost_auth` and `nhost_storage` just have messages indicating they are waiting on Hasura to be ready, and `nhost_hasura` has errors saying that it couldn't connect to `nhost_postgres`.

**Comment by mrinalwahal** [comment] 2022-02-07 03:19
Well, as the logs say - you clearly have a permission issue on your system.

Please take over the directory permissions based on your OS. For example, in UNIX systems use: `chmod` || `chown`.

Then rerun the CLI.

But this is definitely not a bug in the CLI. So, I'm closing this.

**Comment by Herohtar** [comment] 2022-02-07 04:47
> Please take over the directory permissions based on your OS. For example, in UNIX systems use: chmod || chown.

`/var/lib/postgresql/data` is inside the container, so I can't do that.

However, looking at the CLI code, it looks like the CLI tries to mount the local path `./.nhost/main/db_data` as the volume that maps to `/var/lib/postgresql/data` inside the container. Looking at that folder, it is already owned by me and I have full permissions:
```
[herohtar@thalion nhost-test]$ ls -l .nhost/main/
total 0
drwxrwxr-x. 1 herohtar herohtar  8 Feb  5 16:14 custom
drwxrwxr-x. 1 herohtar herohtar  0 Feb  5 16:14 db_data
drwxrwxr-x. 1 herohtar herohtar 20 Feb  5 16:14 minio
```

**Comment by mrinalwahal** [comment] 2022-02-07 07:28
Try running the CLI with `sudo` permissions. And tell me if that does something.

**Comment by Herohtar** [comment] 2022-02-07 07:35
No change in status; still the same errors in every place.

**Comment by nunopato** [comment] 2022-02-24 22:31
@Herohtar I am not able to replicate this issue. Are you able to launch a Postgres container without using the CLI?

**Comment by Herohtar** [comment] 2022-02-24 22:58
@nunopato No, that also fails with the same error. The problem is that Postgres tries to `chown` and `chmod` the database folder, which doesn't work with the permissions that Podman has. However, I am able to run Postgres with Podman if I mount the volume with the `Z` option (eg, `-v /home/user/project/data:/var/lib/postgresql/data:Z`). If I [modify the CLI](https://github.com/Herohtar/cli/commit/67abb1007e251f400186da5926d2fa8fcab9d2f3) to use the same option to mount the volume for its Postgres container, it works.

**Closed** 2022-04-12 09:53 UTC

**Comment by joshua1** [comment] 2022-04-22 15:29
@Herohtar  is your fix now part of the latest CLI version ? i am still experiencing the same issue . And i have the latest CLI installed. chown and chmod not fixing the issue here. every where i have looked indicates only the :z option works

**Comment by Herohtar** [comment] 2022-04-22 16:36
@joshua1 Yes. I don't know which specific version it was added in, but if you use the current latest (`v0.6.6`) it should work.

**Comment by joshua1** [comment] 2022-04-23 07:21
@Herohtar , i am using the current version and still no joy. still getting  
```
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
```
I will delete all downloaded images and try again

**Comment by joshua1** [comment] 2022-04-23 07:42
Made no difference downloading new images.

**Comment by dbarrosop** [comment] 2022-04-23 07:58
@joshua1 the fix wasn't related to the images, it is related to the cli itself:

https://github.com/nhost/cli/pull/158

Which OS and container engine are you using? This particular issue that was solved was related to podman. If you are running some other OS or engine that might be the cause, for instance, I am aware that colima, lima and other qemu-based container solutions for non-linux system also suffers this same issue and was fixed very recently (still not released though)
